# Generated by Django 2.2.4 on 2019-08-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='time',
        ),
        migrations.AlterField(
            model_name='evento',
            name='ending_date',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='starting_date',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
    ]
