# Generated by Django 2.2.4 on 2020-01-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['starting_date']},
        ),
    ]
