# Generated by Django 2.2.4 on 2020-01-12 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20200111_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='slug',
        ),
        migrations.AddField(
            model_name='evento',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
