# Generated by Django 2.2.4 on 2019-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190814_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
