# Generated by Django 2.2.4 on 2020-01-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20200112_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='time',
        ),
    ]
