# Generated by Django 2.2.4 on 2020-01-12 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_evento_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
