"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import os

SECRET_KEY = 'c6zvbqo(vhx21n5+^8norkywz(+5(-l!q7v)vcb0-b#e-dk0wc'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_apscheduler",
    'rangefilter',
    'rest_framework',
    'corsheaders',
    'knox',
    'accounts',
    'userprofile.apps.UserprofileConfig',
    'eventos',
    'financeiro',
    'horariod',
]

SCHEDULER_CONFIG = {
    "apscheduler.jobstores.default": {
        "class": "django_apscheduler.jobstores:DjangoJobStore"
    },
    'apscheduler.executors.processpool': {
        "type": "threadpool"
    },
}
SCHEDULER_AUTOSTART = True


REST_FRAMEWORK = {
    # "DATE_INPUT_FORMATS": ['%d-%m-%Y'],
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 900
}

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': 5432,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticdjango')
STATIC_URL = '/staticdjango/'

# CORS_ALLOW_CREDENTIALS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')


# TODO

# 1 - deletar apenas aulas de hj pra frente check
# 2 - mensagem “Esta é ultima aula de mês e não poderá ser remarcada!”
# 3 - aula reposição em azul
# 4 - alterar Pagamentos automaticamente quando alterado tanto plano quanto a data de pagamento
# 5 - mostrar horario que aluno desmarcou a aula
# 6 - mudar de cor no aplicativo aulas que precisam ser remarcadas
# 7 - mandar email desejando feliz aniversário
# 8 - mandar email um dia antes pra natalia sobre aniversário
# 9 - aluno poder remarcar suas aulas
# 10 - enviar email um dia antes do pagamento? 
# 11 - manter aba dos pagamentos

# 1-Colocar R nas aulas de reposição (na relação de aulas do aplicativo). E quando for desmarcar colocar a frase: “Aula de reposição não pode ser remarcada.”9
# 2- Dar a opção de agendar reposição fora do pacote (caso de atestado) sem alterar a contagem das aulas. Somente no admin.
# 3- Aba “Planos” - Imagem
# 4- Abra “Regras de funcionamento” - Imagem
# 5- Aparecer o pagamento do ano seguinte (pq tem aluno que paga anual).
# 6- Colocar a busca do evento  (admin) mais fácil, por mês e ano para trocar algum horário que precisar.
# 7- Quando eu faço um cadastro e agendo as aulas de uma aluno do dia 22/09, mas vai começar só 10/10. O sistema já lança a aula dela fixa desde o dia 22/09. Então ele precisa lançar só a partir do dia 10/10. Fica ocupando um horário que outra pessoa pode agendar a reposição.
# 8- Aula experimental: forma de agendar sem cadastro (nome do aluno e professora apenas) e ficar cor diferente.
# 9- “Cadastrar aula” e “deletar aula” aparecer apenas os alunos ativos.


# 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