# Generated by Django 2.2.4 on 2020-01-11 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=100)),
                ('instagram', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('aulas_remarcadas', models.IntegerField(default=0)),
                ('plano', models.CharField(choices=[('8 Aulas', '8 Aulas'), ('10 Aulas', '10 Aulas'), ('12 Aulas', '12 Aulas')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
