# Generated by Django 2.2.4 on 2020-01-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plano',
            field=models.CharField(choices=[('4 Aulas', '4 Aulas'), ('8 Aulas', '8 Aulas'), ('12 Aulas', '12 Aulas')], max_length=20),
        ),
    ]
